version: '3.8'

volumes:
  logs:
  prom_data:

services:
  go-observability:
    image: max-weis/go-observability
    build:
      context: ./src
    volumes:
      - logs:/app/log
    ports:
      - 8000:8000

  #prometheus:
  #  image: prom/prometheus:v2.1.0
  #  volumes:
  #    - ./prometheus/:/etc/prometheus/
  #    - prom_data:/prometheus
  #  command:
  #    - '--config.file=/etc/prometheus/prometheus.yml'
  #    - '--storage.tsdb.path=/prometheus'
  #    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #    - '--web.console.templates=/usr/share/prometheus/consoles'
  #  ports:
  #    - 9090:9090