server:
  http_listen_port: 8000

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: observability-service
    static_configs:
      - targets:
          - observability-service
        labels:
          job: applogs
          __path__: /app/logs/monitoring.log